import React from 'react';

export const metadata = {
    title: "Contact",
    description: "Generated by create next app",
};

const Contact = () => {
    return (
        <div>
            <h1>Contact</h1>
        </div>
    );
};

export default Contact;