
import React from 'react';

export const metadata = {
    title: "Product",
    description: "Generated by create next app",
};

const ProductsPage = () => {
    return (
        <div>
            <h1>Products Page</h1>

        </div>
    );
};

export default ProductsPage;